<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="IN-SATHEESHNAI" name="regression.TC_AddNewPosition" tests="7" failures="1" timestamp="04 Mar 2019 11:23:36 GMT" time="166.359" errors="0">
  <testcase name="testcase" time="12.164" classname="regression.TC_AddNewPosition"/>
  <testcase name="header" time="4.415" classname="regression.TC_AddNewPosition"/>
  <testcase name="clickondemand" time="4.213" classname="regression.TC_AddNewPosition"/>
  <testcase name="addnewposition" time="32.236" classname="regression.TC_AddNewPosition"/>
  <testcase name="addposition" time="78.581" classname="regression.TC_AddNewPosition"/>
  <testcase name="submitposition" time="34.750" classname="regression.TC_AddNewPosition">
    <failure type="java.lang.AssertionError" message="Position not submiited">
      <![CDATA[java.lang.AssertionError: Position not submiited
at org.testng.Assert.fail(Assert.java:96)
at pages.AddNewPosition.clicksubmitbutton(AddNewPosition.java:378)
at regression.TC_AddNewPosition.submitposition(TC_AddNewPosition.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- submitposition -->
  <testcase name="logout" classname="regression.TC_AddNewPosition">
    <skipped/>
  </testcase> <!-- logout -->
</testsuite> <!-- regression.TC_AddNewPosition -->
